### PR TITLE
Allow tokens to drift away from real time

### PR DESCRIPTION
**Pull request by pavarnos**
Over a period of years, the clock in a physical OTP device drifts slowly away from the exact time because it has no way of syncing with the internet (!). We use Feitian c200 tokens. The manufacturer spec is +- 3 periods (of 30 sec each) _per year_. Most tokens are within that tolerance, but a good number fall outside that. We have about 1200 tokens in use at the moment.

To handle this, we need to store the current token offset in a database along with the token secret. The pull request allows us to pass that offset back in so that a token that has drifted well away from real time can still be used to authenticate. At authentication time, we calculate the current offset and use it to re-calibrate the token. So no matter how much the token drifts over time, if the user keeps using it regularly (every 6 months) they can still log in with it.

We also built a tool that allows users to resync their token: it sets the offset to zero, then accepts a very wide window (about 10 minutes either side) to calculate the initial offset. Once the offset is calculated and saved back to the database, the normal window size of 2 applies for all future logins.

### CODE REVIEW

**Comment by pavarnos** [comment]
we return early from validate() so that if the password is correct, the new offset it set. if it is incorrect, we maintain the current offset value. The previous code was resetting it to 0 on invalid

**Comment by rchouinard** [comment]
> The manufacturer spec is +- 3 periods (of 30 sec each) per year.

That's somewhat surprising, as it means on the high end you expect a drift of +/- 7.5 minutes over 5 years. In this case I can see the utility of this patch. I'll gladly accept it if you could fix the failing tests and perhaps add some tests to ensure proper operation of your patch.

**Comment by pavarnos** [comment]
thanks

i didn't write tests because i was unsure how soon you were going to release v2.0. Just wanted to show you the idea and how it worked in case it was helpful for v2. The code is copied from my own TOTP subclass which as been in production for a year or more.

fwiw the style ci failure was already present? (it is in lines i did not change)?

the travis build fails on php5.3. is there any point supporting php 5.3 now that 5.6 is about to move to security patches only in favour of php 7? 

let me know how best to move forward
and thanks again for the library: we use it every day!

**Comment by rchouinard** [comment]
The style issue isn't a blocker. Support for PHP 5.3+ is important in the 1.x series, but I'll be changing that in the 2.0 series, which I really need to push for testing.

I'll try to get a beta of 2.0 out over the coming weekend. I'll consider whether to include this PR in the current stable, or just push it to 2.0.

**Comment by pavarnos** [comment]
hi. any thoughts on merging this PR or your new beta?

**Comment by rchouinard** [comment]
Closing, as re-implemented in 77f5afd. Unfortunately, GitHub won't let me merge this directly anymore.

**Pull request closed without merging**
